apiVersion: v1
kind: Service
metadata:
  labels:
    name: serf
    role: service
  name: serf
spec:
  clusterIp: "None"
  ports:
    - name: "serf-tcp"
      port: 7946
      targetPort: 7946
      protocol: TCP
    - name: "serf-udp"
      port: 7946
      targetPort: 7946
      protocol: UDP
  selector:
    name: "serf"
