apiVersion: v1
kind: ReplicationController
metadata:
  name: serf
spec:
  replicas: 1
  selector:
    name: "serf"
  template:
    metadata:
      labels:
        name: serf
    spec:
      containers:
      - name: serf
        image: quay.io/jhansen/serf:v0.0.9
        ports:
          - containerPort: 7946
