apiVersion: v1
kind: Pod
metadata:
  labels:
    name: serf
  name: serf
spec:
  containers:
    - name: serf
      image: franzenet/serf:v0.1
      imagePullPolicy: Always
      ports:
        - containerPort: 7946
      env:
            - name: SERF_DISCOVERY_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: serf-vars
                  key: discover_address
      resources:
        limits:
          cpu: "0.1"
