apiVersion: v1
kind: Pod
metadata:
  labels:
    name: serf
  name: serf
spec:
  containers:
    - name: serf
      image: quay.io/jhansen/serf:v0.0.9
      ports:
        - containerPort: 7946
      resources:
        limits:
          cpu: "0.1"
